export const products = [
  {
    id: "1",
    name: "Bacca Bucci® Men's Energy Afterburn Disruptor for Multiple Sports,Fashion, Party & Fun Shoes/Sneakers",
    description: "",
    price: 1199,
    image: [
      "../src/assets/products/casuals/mens/1/img1.jpg",
      "../src/assets/products/casuals/mens/1/img2.jpg",
      "../src/assets/products/casuals/mens/1/img3.jpg",
      "../src/assets/products/casuals/mens/1/img4.jpg",
    ],
    category: "Men",
    subcategory: "Casuals",
    sizes: ["6 UK", "7 UK", "8 UK", "9 UK", "10 UK"],
    date: "",
    bestseller: false,
  },
  {
    id: "2",
    name: "Bacca Bucci Men's Sneaker",
    description: "",
    price: 1199,
    image: [
      "../src/assets/products/casuals/mens/2/img1.jpg",
      "../src/assets/products/casuals/mens/2/img2.jpg",
      "../src/assets/products/casuals/mens/2/img3.jpg",
      "../src/assets/products/casuals/mens/2/img4.jpg",
    ],
    category: "Men",
    subcategory: "Casuals",
    sizes: ["6 UK", "7 UK", "8 UK", "9 UK", "10 UK"],
    date: "",
    bestseller: false,
  },
  {
    id: "3",
    name: "ASIAN Men's MEXICO-11 Casual Sneaker Shoes with Synthetic Upper Lightweight Comfortable Mid Top Sneaker Shoes for Men's & Boy's",
    description: "",
    price: 795,
    image: [
      "../src/assets/products/casuals/mens/3/img1.jpg",
      "../src/assets/products/casuals/mens/3/img2.jpg",
      "../src/assets/products/casuals/mens/3/img3.jpg",
      "../src/assets/products/casuals/mens/3/img4.jpg",
    ],
    category: "Men",
    subcategory: "Casuals",
    sizes: ["6 UK", "7 UK", "8 UK", "9 UK", "10 UK"],
    date: "",
    bestseller: true,
  },
  {
    id: "4",
    name: "7-10 Women's Phylon Sole White Over-Panelled Chunky Sneaker | Anti Slip, Stylish & Comfortable Sneaker Shoes with Elegant Design for Casual Outings, Parties",
    description: "",
    price: 3780,
    image: [
      "../src/assets/products/casuals/womens/1/img1.jpg",
      "../src/assets/products/casuals/womens/1/img2.jpg",
      "../src/assets/products/casuals/womens/1/img3.jpg",
      "../src/assets/products/casuals/womens/1/img4.jpg",
    ],
    category: "Women",
    subcategory: "Casuals",
    sizes: ["5 UK", "5.5 UK", "6 UK", "6.5 UK", "7 UK"],
    date: "",
    bestseller: false,
  },
  {
    id: "5",
    name: "Bacca Bucci Luminara Women's Lightweight Running Shoes with Glow-in-The-Dark Feature - Available in Two Colors, Sizes UK 03-08",
    description: "",
    price: 2099,
    image: [
      "../src/assets/products/casuals/womens/2/img1.jpg",
      "../src/assets/products/casuals/womens/2/img2.jpg",
      "../src/assets/products/casuals/womens/2/img3.jpg",
      "../src/assets/products/casuals/womens/2/img4.jpg",
    ],
    category: "Women",
    subcategory: "Casuals",
    sizes: ["3 UK", "4 UK", "7 UK", "8 UK"],
    date: "",
    bestseller: false,
  },
  {
    id: "6",
    name: "ASIAN Women's Firefly-10 Sports Running,Walking,Gym,Training,Casual Slip-On Lightweight Shoes for Women's & Girl's",
    description: "",
    price: 795,
    image: [
      "../src/assets/products/casuals/womens/3/img1.jpg",
      "../src/assets/products/casuals/womens/3/img2.jpg",
      "../src/assets/products/casuals/womens/3/img3.jpg",
    ],
    category: "Women",
    subcategory: "Casuals",
    sizes: ["4 UK", "5 UK", "6 UK", "7 UK", "8 UK"],
    date: "",
    bestseller: true,
  },
  {
    id: "7",
    name: "ASIAN Women's SUPERFLY-02 Sports Running,Walking & Gym Shoes with Lightweight Soleflex Technology Extra Cushion Casual Lace-Up Shoes for Women's & Girl's",
    description: "",
    price: 999,
    image: [
      "../src/assets/products/sports/womens/1/img1.jpg",
      "../src/assets/products/sports/womens/1/img2.jpg",
      "../src/assets/products/sports/womens/1/img3.jpg",
    ],
    category: "Women",
    subcategory: "Sports",
    sizes: ["4 UK", "5 UK", "6 UK", "7 UK", "8 UK"],
    date: "",
    bestseller: false,
  },
  {
    id: "8",
    name: "SPARX Womens Sl 170 Running Shoe",
    description: "",
    price: 725,
    image: [
      "../src/assets/products/sports/womens/2/img1.jpg",
      "../src/assets/products/sports/womens/2/img2.jpg",
      "../src/assets/products/sports/womens/2/img3.jpg",
    ],
    category: "Women",
    subcategory: "Sports",
    sizes: ["4 UK", "5 UK", "6 UK", "7 UK", "8 UK"],
    date: "",
    bestseller: true,
  },
  {
    id: "9",
    name: "Bacca Bucci Men's Running Shoe",
    description: "",
    price: 1499,
    image: [
      "../src/assets/products/sports/mens/1/img1.jpg",
      "../src/assets/products/sports/mens/1/img2.jpg",
      "../src/assets/products/sports/mens/1/img3.jpg",
    ],
    category: "Men",
    subcategory: "Sports",
    sizes: ["6 UK", "7 UK", "8 UK", "9 UK", "10 UK"],
    date: "",
    bestseller: false,
  },
  {
    id: "10",
    name: "Reebok Mens Stride Runner Running Shoe",
    description: "",
    price: 1469,
    image: [
      "../src/assets/products/sports/mens/2/img1.jpg",
      "../src/assets/products/sports/mens/2/img2.jpg",
      "../src/assets/products/sports/mens/2/img3.jpg",
    ],
    category: "Men",
    subcategory: "Sports",
    sizes: ["6 UK", "7 UK", "8 UK", "9 UK", "10 UK"],
    date: "",
    bestseller: false,
  },
  {
    id: "11",
    name: "ARETTO Expanding Kids Shoes | Everyday Wear Shoes | School Shoes | Casual Shoes | Sports Shoes | Comfortable Shoes for Boys, Girls | Party Shoes",
    description: "",
    price: 2599,
    image: [
      "../src/assets/products/casuals/kids/1/img1.jpg",
      "../src/assets/products/casuals/kids/1/img2.jpg",
      "../src/assets/products/casuals/kids/1/img3.jpg",
    ],
    category: "Kids",
    subcategory: "Casuals",
    sizes: ["2 UK", "3 UK", "4 UK", "5 UK"],
    date: "",
    bestseller: false,
  },
  {
    id: "12",
    name: "Liberty Kids Sport Non Lacing Shoes (TURBO-1E)",
    description: "",
    price: 819,
    image: [
      "../src/assets/products/casuals/kids/2/img1.jpg",
      "../src/assets/products/casuals/kids/2/img2.jpg",
      "../src/assets/products/casuals/kids/2/img3.jpg",
    ],
    category: "Kids",
    subcategory: "Casuals",
    sizes: ["2 UK", "3 UK", "4 UK", "5 UK"],
    date: "",
    bestseller: true,
  },
];
